Install referenced schema in `npm:validate` task
The `npm:validate` task validates the project's `package.json` npm manifest file against its JSON schema to catch any
problems with its data format.

In order to avoid duplication of content, JSON schemas may reference other schemas via the `$ref` keyword. The
`package.json` schema was recently updated to share resources with the `eslintrc.json` schema, which caused the
validation to start failing:

error: can't resolve reference https://json.schemastore.org/eslintrc.json from id #

The solution is to configure the task to download that schema as well and also to provide its path to the avj-cli
validator via an `-r` flag.